# Generated by Django 4.0 on 2022-01-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Ordering', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Category', models.CharField(max_length=100)),
                ('Created_at', models.DateField()),
            ],
        ),
    ]
